CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE invitation_codes (
    code_hash TEXT PRIMARY KEY,
    created_at DOUBLE PRECISION NOT NULL,
    used_by TEXT,
    used_at DOUBLE PRECISION,
    max_uses BIGINT NOT NULL DEFAULT 1,
    use_count BIGINT NOT NULL DEFAULT 0,
    expires_at DOUBLE PRECISION
);

CREATE TABLE invitation_redemptions (
    code_hash TEXT NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id),
    used_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY(code_hash, user_id)
);

CREATE TABLE auth_sessions (
    token_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    created_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    revoked_at DOUBLE PRECISION
);

CREATE TABLE projects (
    id TEXT PRIMARY KEY,
    owner_user_id TEXT NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    instructions TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'archived')),
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    archived_at DOUBLE PRECISION
);

CREATE TABLE conversations (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    project_id TEXT REFERENCES projects(id) ON DELETE RESTRICT,
    title TEXT NOT NULL DEFAULT '新对话',
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    is_pinned BIGINT NOT NULL DEFAULT 0 CHECK (is_pinned IN (0, 1)),
    archived_at DOUBLE PRECISION
);

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    payload TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    metadata TEXT NOT NULL DEFAULT '{}',
    created_at DOUBLE PRECISION NOT NULL
);

-- Temporary import table. Migration 0004 converts attributable rows into
-- memory_items, archives unattributable rows, then removes this table.
CREATE TABLE memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE assets (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    sha256 TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    storage_key TEXT NOT NULL,
    width BIGINT NOT NULL,
    height BIGINT NOT NULL,
    size_bytes BIGINT NOT NULL,
    captured_at DOUBLE PRECISION,
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE(user_id, sha256)
);

CREATE TABLE memory_items (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    scope_type TEXT NOT NULL DEFAULT 'personal'
        CHECK (scope_type IN ('personal', 'project')),
    project_id TEXT REFERENCES projects(id) ON DELETE RESTRICT,
    conversation_id TEXT REFERENCES conversations(id) ON DELETE SET NULL,
    source_turn_id BIGINT REFERENCES turns(id) ON DELETE SET NULL,
    source_response_id TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'visual',
    user_note TEXT NOT NULL,
    visual_summary TEXT NOT NULL DEFAULT '',
    cover_asset_id TEXT,
    captured_at DOUBLE PRECISION,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    is_pinned BIGINT NOT NULL DEFAULT 0 CHECK (is_pinned IN (0, 1)),
    archived_at DOUBLE PRECISION,
    CHECK (
        (scope_type = 'personal' AND project_id IS NULL) OR
        (scope_type = 'project' AND project_id IS NOT NULL)
    )
);

CREATE TABLE memory_assets (
    memory_id TEXT NOT NULL REFERENCES memory_items(id) ON DELETE CASCADE,
    asset_id TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    ordinal BIGINT NOT NULL,
    is_cover BIGINT NOT NULL DEFAULT 0 CHECK (is_cover IN (0, 1)),
    PRIMARY KEY(memory_id, asset_id)
);

CREATE TABLE todos (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    project_id TEXT REFERENCES projects(id) ON DELETE RESTRICT,
    memory_id TEXT REFERENCES memory_items(id) ON DELETE SET NULL,
    conversation_id TEXT REFERENCES conversations(id) ON DELETE SET NULL,
    source_turn_id BIGINT REFERENCES turns(id) ON DELETE SET NULL,
    source_response_id TEXT,
    title TEXT NOT NULL,
    visual_summary TEXT NOT NULL DEFAULT '',
    cover_asset_id TEXT REFERENCES assets(id) ON DELETE SET NULL,
    due_at DOUBLE PRECISION,
    completed_at DOUBLE PRECISION,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE turn_attachments (
    turn_id BIGINT NOT NULL REFERENCES turns(id) ON DELETE CASCADE,
    asset_id TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    memory_id TEXT REFERENCES memory_items(id) ON DELETE SET NULL,
    todo_id TEXT REFERENCES todos(id) ON DELETE SET NULL,
    caption TEXT NOT NULL DEFAULT '',
    ordinal BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY(turn_id, asset_id)
);

CREATE TABLE memory_tool_executions (
    response_id TEXT NOT NULL,
    tool_call_id TEXT NOT NULL,
    memory_id TEXT NOT NULL REFERENCES memory_items(id) ON DELETE CASCADE,
    PRIMARY KEY(response_id, tool_call_id)
);

CREATE TABLE todo_tool_executions (
    response_id TEXT NOT NULL,
    tool_call_id TEXT NOT NULL,
    todo_id TEXT NOT NULL REFERENCES todos(id) ON DELETE CASCADE,
    PRIMARY KEY(response_id, tool_call_id)
);

CREATE TABLE project_resources (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    asset_id TEXT REFERENCES assets(id) ON DELETE SET NULL,
    extracted_text TEXT NOT NULL DEFAULT '',
    metadata JSONB NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'ready',
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    archived_at DOUBLE PRECISION
);

CREATE TABLE retrieval_documents (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    scope_type TEXT NOT NULL CHECK (scope_type IN ('personal', 'project')),
    project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
    source_type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'active',
    occurred_at DOUBLE PRECISION,
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE(source_type, source_id),
    CHECK (
        (scope_type = 'personal' AND project_id IS NULL) OR
        (scope_type = 'project' AND project_id IS NOT NULL)
    )
);

CREATE TABLE retrieval_chunks (
    id TEXT PRIMARY KEY,
    document_id TEXT NOT NULL REFERENCES retrieval_documents(id) ON DELETE CASCADE,
    ordinal BIGINT NOT NULL,
    content TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    token_count BIGINT,
    importance DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE(document_id, ordinal),
    UNIQUE(document_id, content_hash)
);

CREATE TABLE chunk_embeddings (
    chunk_id TEXT PRIMARY KEY REFERENCES retrieval_chunks(id) ON DELETE CASCADE,
    model TEXT NOT NULL,
    dimensions BIGINT NOT NULL,
    embedding vector(384) NOT NULL,
    content_hash TEXT NOT NULL,
    embedded_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE memory_facts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    scope_type TEXT NOT NULL CHECK (scope_type IN ('personal', 'project')),
    project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    canonical_key TEXT NOT NULL,
    summary TEXT NOT NULL,
    salience DOUBLE PRECISION NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    explicit BIGINT NOT NULL DEFAULT 0 CHECK (explicit IN (0, 1)),
    activation_status TEXT NOT NULL
        CHECK (activation_status IN ('active', 'pending_confirmation', 'rejected', 'superseded')),
    supersedes_id TEXT REFERENCES memory_facts(id) ON DELETE SET NULL,
    valid_from DOUBLE PRECISION,
    valid_to DOUBLE PRECISION,
    last_recalled_at DOUBLE PRECISION,
    recall_count BIGINT NOT NULL DEFAULT 0,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    CHECK (
        (scope_type = 'personal' AND project_id IS NULL) OR
        (scope_type = 'project' AND project_id IS NOT NULL)
    )
);

CREATE TABLE memory_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fact_id TEXT NOT NULL REFERENCES memory_facts(id) ON DELETE CASCADE,
    chunk_id TEXT REFERENCES retrieval_chunks(id) ON DELETE SET NULL,
    turn_id BIGINT REFERENCES turns(id) ON DELETE SET NULL,
    memory_item_id TEXT REFERENCES memory_items(id) ON DELETE SET NULL,
    asset_id TEXT REFERENCES assets(id) ON DELETE SET NULL
);

CREATE TABLE memory_jobs (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
    conversation_id TEXT REFERENCES conversations(id) ON DELETE CASCADE,
    job_type TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'pending',
    attempts BIGINT NOT NULL DEFAULT 0,
    run_after DOUBLE PRECISION NOT NULL,
    locked_at DOUBLE PRECISION,
    last_error TEXT,
    idempotency_key TEXT NOT NULL UNIQUE,
    created_at DOUBLE PRECISION NOT NULL,
    finished_at DOUBLE PRECISION
);

CREATE TABLE memory_usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id TEXT NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id),
    project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
    chunk_id TEXT REFERENCES retrieval_chunks(id) ON DELETE SET NULL,
    fact_id TEXT REFERENCES memory_facts(id) ON DELETE SET NULL,
    score DOUBLE PRECISION NOT NULL,
    rank BIGINT NOT NULL,
    reason TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX idx_turns_session ON turns(session_id, id);
CREATE INDEX idx_events_session ON events(session_id, id);
CREATE INDEX idx_memories_session ON memories(session_id, id);
CREATE INDEX idx_auth_sessions_user ON auth_sessions(user_id, expires_at);
CREATE INDEX idx_projects_owner ON projects(owner_user_id, updated_at DESC);
CREATE INDEX idx_conversations_user ON conversations(user_id, updated_at DESC);
CREATE INDEX idx_conversations_project ON conversations(project_id, updated_at DESC);
CREATE INDEX idx_memory_items_user ON memory_items(user_id, created_at DESC);
CREATE INDEX idx_memory_items_project ON memory_items(project_id, created_at DESC);
CREATE INDEX idx_memory_assets_memory ON memory_assets(memory_id, ordinal);
CREATE INDEX idx_turn_attachments_turn ON turn_attachments(turn_id, ordinal);
CREATE INDEX idx_todos_user_due ON todos(user_id, completed_at, due_at);
CREATE INDEX idx_todos_project ON todos(project_id, completed_at, due_at);
CREATE INDEX idx_resources_project ON project_resources(project_id, updated_at DESC);
CREATE INDEX idx_retrieval_scope ON retrieval_documents(user_id, scope_type, project_id, status);
CREATE INDEX idx_retrieval_chunks_trgm ON retrieval_chunks USING GIN (content gin_trgm_ops);
CREATE INDEX idx_memory_facts_scope ON memory_facts(user_id, scope_type, project_id, activation_status);
CREATE INDEX idx_memory_jobs_ready ON memory_jobs(status, run_after);
