CREATE TABLE meetings (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    conversation_id TEXT REFERENCES conversations(id) ON DELETE SET NULL,
    mode TEXT NOT NULL CHECK (mode IN ('audio', 'video')),
    status TEXT NOT NULL DEFAULT 'recording'
        CHECK (status IN ('recording', 'processing', 'ready', 'failed')),
    started_at DOUBLE PRECISION NOT NULL,
    ended_at DOUBLE PRECISION,
    duration_seconds BIGINT,
    title TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    generated_at DOUBLE PRECISION,
    last_error TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX meetings_user_started_idx
    ON meetings(user_id, started_at DESC);

CREATE TABLE meeting_transcript_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    ordinal BIGINT NOT NULL,
    UNIQUE(meeting_id, ordinal)
);

CREATE TABLE meeting_action_items (
    id TEXT PRIMARY KEY,
    meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    due_at DOUBLE PRECISION,
    todo_id TEXT REFERENCES todos(id) ON DELETE SET NULL,
    ordinal BIGINT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE(meeting_id, ordinal)
);

ALTER TABLE todos
    ADD COLUMN meeting_id TEXT REFERENCES meetings(id) ON DELETE SET NULL;

CREATE INDEX todos_meeting_idx ON todos(meeting_id);
